/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_design_chenxiao_jnitest_NativeMoce */

#ifndef _Included_com_design_chenxiao_jnitest_NativeMoce
#define _Included_com_design_chenxiao_jnitest_NativeMoce
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_design_chenxiao_jnitest_NativeMoce
 * Method:    getHe
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_design_chenxiao_jnitest_NativeMoce_getHe
  (JNIEnv *env, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
